var webpack = require('webpack');

module.exports={
	entry:['./src/script/main.js'],
	output:{
		path:__dirname + '/dist/js',
		filename:'bundle.js'
	},
	devServer:{
		inline:true,
		port:3002
	},
	module:{
		loaders:[
			{
				test:/\.js$/,
				exclude:/node_modules/,
				use:{
					loader:'babel-loader',
					options:{
					presets:['react','latest']
					}
				}
			},
			{
				test:/\.css$/,
				//loader:['sass-loader','style-loader','css-loader?modules'],
				use:[
					{
						loader:'style-loader'
					},
					{
						loader:'css-loader',
						options:{
							modules: true,
							localIdentName:'[name]__[local]--[hash:base64:5]'
						}
					}
					]
			},
			{
				test:/\.scss$/,
				//loader:['sass-loader','style-loader','css-loader?modules'],
				use:[
					{
						loader:'style-loader'
					},
					{
						loader:'css-loader',
						options:{
							modules: true,
							localIdentName:'[name]__[local]--[hash:base64:5]'
						}
					},
					{
						loader:'sass-loader'
					}
				]
			}
		]
	}
}